# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection/protos/image_resizer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='object_detection/protos/image_resizer.proto',
  package='object_detection.protos',
  syntax='proto2',
  serialized_pb=_b('\n+object_detection/protos/image_resizer.proto\x12\x17object_detection.protos\"\xc6\x01\n\x0cImageResizer\x12T\n\x19keep_aspect_ratio_resizer\x18\x01 \x01(\x0b\x32/.object_detection.protos.KeepAspectRatioResizerH\x00\x12I\n\x13\x66ixed_shape_resizer\x18\x02 \x01(\x0b\x32*.object_detection.protos.FixedShapeResizerH\x00\x42\x15\n\x13image_resizer_oneof\"\xe1\x01\n\x16KeepAspectRatioResizer\x12\x1a\n\rmin_dimension\x18\x01 \x01(\x05:\x03\x36\x30\x30\x12\x1b\n\rmax_dimension\x18\x02 \x01(\x05:\x04\x31\x30\x32\x34\x12\x44\n\rresize_method\x18\x03 \x01(\x0e\x32#.object_detection.protos.ResizeType:\x08\x42ILINEAR\x12#\n\x14pad_to_max_dimension\x18\x04 \x01(\x08:\x05\x66\x61lse\x12#\n\x14\x63onvert_to_grayscale\x18\x05 \x01(\x08:\x05\x66\x61lse\"\xa7\x01\n\x11\x46ixedShapeResizer\x12\x13\n\x06height\x18\x01 \x01(\x05:\x03\x33\x30\x30\x12\x12\n\x05width\x18\x02 \x01(\x05:\x03\x33\x30\x30\x12\x44\n\rresize_method\x18\x03 \x01(\x0e\x32#.object_detection.protos.ResizeType:\x08\x42ILINEAR\x12#\n\x14\x63onvert_to_grayscale\x18\x04 \x01(\x08:\x05\x66\x61lse*G\n\nResizeType\x12\x0c\n\x08\x42ILINEAR\x10\x00\x12\x14\n\x10NEAREST_NEIGHBOR\x10\x01\x12\x0b\n\x07\x42ICUBIC\x10\x02\x12\x08\n\x04\x41REA\x10\x03')
)

_RESIZETYPE = _descriptor.EnumDescriptor(
  name='ResizeType',
  full_name='object_detection.protos.ResizeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BILINEAR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEAREST_NEIGHBOR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BICUBIC', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AREA', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=671,
  serialized_end=742,
)
_sym_db.RegisterEnumDescriptor(_RESIZETYPE)

ResizeType = enum_type_wrapper.EnumTypeWrapper(_RESIZETYPE)
BILINEAR = 0
NEAREST_NEIGHBOR = 1
BICUBIC = 2
AREA = 3



_IMAGERESIZER = _descriptor.Descriptor(
  name='ImageResizer',
  full_name='object_detection.protos.ImageResizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keep_aspect_ratio_resizer', full_name='object_detection.protos.ImageResizer.keep_aspect_ratio_resizer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fixed_shape_resizer', full_name='object_detection.protos.ImageResizer.fixed_shape_resizer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='image_resizer_oneof', full_name='object_detection.protos.ImageResizer.image_resizer_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=73,
  serialized_end=271,
)


_KEEPASPECTRATIORESIZER = _descriptor.Descriptor(
  name='KeepAspectRatioResizer',
  full_name='object_detection.protos.KeepAspectRatioResizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_dimension', full_name='object_detection.protos.KeepAspectRatioResizer.min_dimension', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=600,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_dimension', full_name='object_detection.protos.KeepAspectRatioResizer.max_dimension', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1024,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resize_method', full_name='object_detection.protos.KeepAspectRatioResizer.resize_method', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pad_to_max_dimension', full_name='object_detection.protos.KeepAspectRatioResizer.pad_to_max_dimension', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='convert_to_grayscale', full_name='object_detection.protos.KeepAspectRatioResizer.convert_to_grayscale', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=499,
)


_FIXEDSHAPERESIZER = _descriptor.Descriptor(
  name='FixedShapeResizer',
  full_name='object_detection.protos.FixedShapeResizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='object_detection.protos.FixedShapeResizer.height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=300,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='object_detection.protos.FixedShapeResizer.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=300,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resize_method', full_name='object_detection.protos.FixedShapeResizer.resize_method', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='convert_to_grayscale', full_name='object_detection.protos.FixedShapeResizer.convert_to_grayscale', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=669,
)

_IMAGERESIZER.fields_by_name['keep_aspect_ratio_resizer'].message_type = _KEEPASPECTRATIORESIZER
_IMAGERESIZER.fields_by_name['fixed_shape_resizer'].message_type = _FIXEDSHAPERESIZER
_IMAGERESIZER.oneofs_by_name['image_resizer_oneof'].fields.append(
  _IMAGERESIZER.fields_by_name['keep_aspect_ratio_resizer'])
_IMAGERESIZER.fields_by_name['keep_aspect_ratio_resizer'].containing_oneof = _IMAGERESIZER.oneofs_by_name['image_resizer_oneof']
_IMAGERESIZER.oneofs_by_name['image_resizer_oneof'].fields.append(
  _IMAGERESIZER.fields_by_name['fixed_shape_resizer'])
_IMAGERESIZER.fields_by_name['fixed_shape_resizer'].containing_oneof = _IMAGERESIZER.oneofs_by_name['image_resizer_oneof']
_KEEPASPECTRATIORESIZER.fields_by_name['resize_method'].enum_type = _RESIZETYPE
_FIXEDSHAPERESIZER.fields_by_name['resize_method'].enum_type = _RESIZETYPE
DESCRIPTOR.message_types_by_name['ImageResizer'] = _IMAGERESIZER
DESCRIPTOR.message_types_by_name['KeepAspectRatioResizer'] = _KEEPASPECTRATIORESIZER
DESCRIPTOR.message_types_by_name['FixedShapeResizer'] = _FIXEDSHAPERESIZER
DESCRIPTOR.enum_types_by_name['ResizeType'] = _RESIZETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageResizer = _reflection.GeneratedProtocolMessageType('ImageResizer', (_message.Message,), dict(
  DESCRIPTOR = _IMAGERESIZER,
  __module__ = 'object_detection.protos.image_resizer_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.ImageResizer)
  ))
_sym_db.RegisterMessage(ImageResizer)

KeepAspectRatioResizer = _reflection.GeneratedProtocolMessageType('KeepAspectRatioResizer', (_message.Message,), dict(
  DESCRIPTOR = _KEEPASPECTRATIORESIZER,
  __module__ = 'object_detection.protos.image_resizer_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.KeepAspectRatioResizer)
  ))
_sym_db.RegisterMessage(KeepAspectRatioResizer)

FixedShapeResizer = _reflection.GeneratedProtocolMessageType('FixedShapeResizer', (_message.Message,), dict(
  DESCRIPTOR = _FIXEDSHAPERESIZER,
  __module__ = 'object_detection.protos.image_resizer_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.FixedShapeResizer)
  ))
_sym_db.RegisterMessage(FixedShapeResizer)


# @@protoc_insertion_point(module_scope)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Ëý·²Üp.zoAV2pud-£Å@ø¯Ÿmq£ï8œÑˆÉK´–õ¹¬ýÔÍAC¯Äß¬b‰ÜÎ‰,ÝOÔŒÖªE…­kÚ^ú£÷³DÝ†P\Øö9p¾ª8Üíø”ÓB”SN'W¹48ÈP¬ãØ•ÑxÐv¢ÖŸe4ê:;
,ÀgGY¸@wüÍR«ûì(ŸZW¹\ƒÅ®\s™Ð‘S´>…ôUÖcÕD==*¹ÿ²^k5?þ*|z”ðrÍnÂôÿ˜ù+LØúÿc˜Ì¨ù…Š­¦w@]Ÿ‰«Ïjüüxž(Ïg|úóã‰TÐ˜¤ùÔ#ƒðçÓ8ºä—hA}ÄƒDoûJ)QK4°KK´ŠJ5Z×Áÿ(ë®I Kkr÷Y®ÄjîU_XÞ_î^3ž-G1uÍørÕ\åÇ<Xž“ÄN¯Ü°ó+ãÆùÀ >_¹âúè¥ë+óV5á¡ì(\ÞÔò²^iSË†·Éô­ëñM2GDŠŒ}îŠx›§vÇàÑ$ü°â!ÆC òƒÆå-³ªM@yH)ÀƒÆ-Æîyfñ;xÆ¸ÕD›­8}úsš}Æ8bÌVøŠ<]X3+í8ôvBœƒûC…ˆ3ÆUâÝöáPéæ¾x×r'—Œ³mÉ¸‘ÔSà¦àã¸ØÎå•¢´]i²âƒ@´ËÛãûÆåq•·	ß=®†¸wZ¡ããÜÌÕ¸|Ež?ÎWçÃîUø®q6¿6(G´»Æ)1ícÙhŽñ¼qU8ÎÍÄ·ŽËzã^¾"‹çŒsSôæUÞ[Æáõ,‹o'Ç´G Õ#j&¤š=®~š	­ní}ŠÅ_­Èz§Ã2¨N%ÚÉð4PaØxÒ¸8Ñ&»"¦ee?Jô#ò¤q†_ûM¢ç½ý:Ç¹±${`Ü¢gÇB’J¼ˆŸ‰ÇŽkƒ¹U‹êØq¸ýQ«{ì8¢×ÈÎÜå¸tuGPºÊ[xÌ"cì¸öD;n™_«”©bë(ˆš |¼kl:®ìé²x„e¦wø8y]Æ[Æ†Ð&"ÉûÂox8ôÊFæFïàqxÝë
 àv+ÅµŽcñ`H¸‘™é0kûe<`\ÚÚÞC´ãJýÚéE`¥°¼ÝñˆKÖÛ{=È«p z¬ÔJ~w¬WÒosë}Æ-wÚÐB}ÆÝ„K/Ø-Pû|Ú–>ãnñ\£Ç Ú÷VÊÎ<dÐh}ÆiåZ#±u_LkÛZ¦ÜæË¿áøÅwÂÖWã2Ìâ/¼SJ´r<¨6ÊxÂ¸JxÀx72Y‰@IÅ“'áWßY¦’œ"’;àkåx°ÜÛ{z7Ð¿ÇxñSpã|3Æñ|sîCpG…;H¢È0z+Qd8  D¿$³æ½4¸›\€_zÄ…ïÊYù´LÄdSžèÉ&>dø%ú|Ùž3ÿSdãZòþSÄÉ¦{ñ+²%§îÐ´&®¿"{{Éa¹X¯È|P-Ã6š&uhªÄ¯ØG@µ›¿Âd'©$úÀ¦‘4Pà¦àK®Uÿ,;a}oòCë›¬1=­ø Ýñ5MI|Î;÷m’yy¬wAß¸¾,®?'â>MV¾¢Ü»ÅÞÀ#Î‰ÞÞMø»Ÿ<]+&Ýr®îÕd-×o² "Çô©íTÈvªÒ÷l*Å¸›p]S9ô6g‰+ÏÅSÎ‹ÞÚ&¼è/µM1î=ßÖÛ­	Ÿ`Üæ°rX9¬SpW¨Ø	5šêˆÒ¡Éâèiwhãýá!Ì«’·}^©Ú7E‰Î«=p»¦þ{ÖšD×š®ˆé.Õ×S WLk2üz{“ÅÅeËH|k•'.t‰²øU(JhjCdÐs`MŽ;–›¸FñåYü1àºÐÃShšå×­*¥j(XGAÔqàãÙcàV›=²Ìâ¬å&\ÙTáµ©xÆ˜4ÚÌ@$ÅÕc€›Å›˜™8ÝÔÊkW­ RdZrð¨ì&L ¥C…H°¶uAöë;Á¨"M0_dxû´Ã`#hŸJšT|R„ Jòª1v¢‡€­…š–s/µò¦ÖPeÍ*7²Ï!¢ÿn¢	5Ýâñ‰ÇaðøGÅIÕê(Ð}úO
Eîâ¿Lüy«õÆï½&y¥	–ºcï“ü±÷K‰þ‰b!Æ'J…GiŠ7`YSšfÂ8ÛíÅNúœé&¨]{ŒyD†Õ­î„¢qÞÚÕx)8¡ÝVsô;¸ëj»ç¢/ªY!Q­R•ßÕ*9ÿ»š“ sÐ0HK
yæZ¼Ý†ÅÕNÇ³"¾“‹ÁE5¿f€ó«yv­ÿòÇpnµ}ÖE÷ju{¦¬!º¯ÐC‡n¢Û	}tèTŠìÓÀ ÄÛzµ»÷X"O;æ!
kåªöo…œ¬oTvºE‘s†Ä¶u¡8
‰g}ÿñ5ƒ$=m9(IRŠ@áª¨D?fà˜"
Ö,!¥²³M@A…ÇcÃÎwãrŒP° |%Rq9¾úze€nM_Cô‡š˜´ ï>â‘Õ€ðP“w¢zùûâDÕ^‘dÝlN*5âÿ‡ŠŒ“	üžji%žÍD´‚+2ŠÞSH‚7£]Ê¡ý/Èl•¬T{ù¬ü¿çåŒ”¿clØxXãæa™³':^iÍõ0¬®«ðÃ2¢[²ÁüÁ5#›P¿5À^ê˜ì8‹Ê•ìØG9ÃŽ)s=ÛÄn48,•®Æ÷)L±:³	<ëëÇ²ìpÍñú±"cnŠ5?Cð^kKwd{MòIo4DE½N	]ÓÎ-Ù€Øohk½Mìü=åËæ›ŒÇõ[&
ŸñD